import type { Metadata } from "next";
import Link from "next/link";
import { FileText, CheckCircle, Clock, Shield } from "lucide-react";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Duplicate RC Issuance | EZRTO - Fast RC Replacement Service",
  description: "Get a duplicate RC if the original is lost. Quick and hassle-free replacement process with doorstep service. Official documentation guaranteed.",
  keywords: "duplicate RC, lost RC replacement, RC duplicate, vehicle registration duplicate, RTO duplicate RC",
  alternates: {
    canonical: "https://ezrto.in/services/duplicate-rc",
  },
};

const features = [
  {
    icon: FileText,
    title: "Lost RC Replacement",
    description: "Quick replacement for lost, stolen, or damaged RC documents"
  },
  {
    icon: Shield,
    title: "Official Documentation", 
    description: "Legally valid duplicate RC with proper RTO endorsement"
  },
  {
    icon: Clock,
    title: "Fast Processing",
    description: "Expedited processing to get your duplicate RC quickly"
  },
  {
    icon: CheckCircle,
    title: "Doorstep Service",
    description: "Document pickup and delivery at your convenience"
  }
];

const processSteps = [
  {
    step: "1",
    title: "Document Verification",
    description: "Submit required documents for RC duplicate application"
  },
  {
    step: "2", 
    title: "Application Processing",
    description: "We handle all RTO formalities and paperwork"
  },
  {
    step: "3",
    title: "RC Generation",
    description: "Official duplicate RC is generated by RTO"
  },
  {
    step: "4",
    title: "Delivery",
    description: "Secure delivery of your duplicate RC to your doorstep"
  }
];

export default function DuplicateRCPage() {
  return (
    <div className="min-h-screen bg-white">
      <Header />
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          Duplicate RC Issuance Service
        </h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          Get a duplicate RC if the original is lost, stolen, or damaged. 
          Our quick and hassle-free replacement process ensures you get 
          official documentation without any delays.
        </p>
      </div>

      <section className="mb-16">
        <h2 className="text-3xl font-bold text-center mb-8">Why Choose Our Duplicate RC Service?</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <div key={index} className="text-center p-6 bg-white rounded-lg shadow-md">
              <feature.icon className="w-12 h-12 text-blue-600 mx-auto mb-4" />
              <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
              <p className="text-gray-600">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mb-16">
        <h2 className="text-3xl font-bold text-center mb-8">How It Works</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {processSteps.map((step, index) => (
            <div key={index} className="text-center">
              <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                {step.step}
              </div>
              <h3 className="text-lg font-semibold mb-2">{step.title}</h3>
              <p className="text-gray-600">{step.description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mb-16 bg-gray-50 p-8 rounded-lg">
        <h2 className="text-3xl font-bold text-center mb-8">Benefits of Our Service</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h3 className="text-xl font-semibold mb-4">For Lost RC</h3>
            <ul className="space-y-2 text-gray-600">
              <li> Quick replacement without lengthy procedures</li>
              <li> No need to visit RTO office multiple times</li>
              <li> Expert guidance throughout the process</li>
              <li> Secure document handling</li>
            </ul>
          </div>
          <div>
            <h3 className="text-xl font-semibold mb-4">For Damaged RC</h3>
            <ul className="space-y-2 text-gray-600">
              <li> Immediate replacement for damaged documents</li>
              <li> Proper verification of damage</li>
              <li> Fast-track processing available</li>
              <li> Doorstep pickup and delivery</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="text-center bg-blue-600 text-white p-8 rounded-lg">
        <h2 className="text-3xl font-bold mb-4">Need a Duplicate RC?</h2>
        <p className="text-xl mb-6">Get started with our hassle-free duplicate RC service today!</p>
        <Link 
          href="/contact" 
          className="bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-100 transition"
        >
          Get Started Now
        </Link>
      </section>

      <section className="mt-16">
        <h2 className="text-3xl font-bold text-center mb-8">Related Services</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Link href="/services/hypothecation-termination" className="p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition">
            <h3 className="text-lg font-semibold mb-2">Hypothecation Termination</h3>
            <p className="text-gray-600">Remove loan records from your vehicle RC</p>
          </Link>
          <Link href="/services/ownership-transfer" className="p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition">
            <h3 className="text-lg font-semibold mb-2">Ownership Transfer</h3>
            <p className="text-gray-600">Handle RC ownership transfer process</p>
          </Link>
          <Link href="/services/address-change" className="p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition">
            <h3 className="text-lg font-semibold mb-2">Address Change on RC</h3>
            <p className="text-gray-600">Update your address on vehicle RC</p>
          </Link>
        </div>
      </section>
      <Footer/>
      </div>
  );
}
